---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webhookdeployemnt
  namespace: webhookrelay
spec:
  gateways:
    - istio-system/ingressgateway
  hosts:
    - web-hook-relay.spl.guru
  http:
    - route:
        - destination:
            host: webhookproxy-service
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webhookproxy-service
  namespace: webhookrelay
spec:
  selector:
    app: webhookproxy
  ports:
    - name: http-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookproxy-deployment
  namespace: webhookrelay
  labels:
    app: webhookproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhookproxy
  template:
    metadata:
      labels:
        app: webhookproxy
    spec:
      containers:
        - name: main
          image: rfaircloth/webhook2hec:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: key
# rfaircloth/webhookproxy:tagname
